// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XR50TrainingAssetRepo.Data;

#nullable disable

namespace XR50TrainingAssetRepo.Migrations.Training
{
    [DbContext(typeof(XR50TrainingContext))]
    partial class XR50TrainingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.AIAssistantMaterialAssetJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AIAssistantMaterialId")
                        .HasColumnType("int");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("JobId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pending");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("AIAssistantMaterialId", "AssetId")
                        .IsUnique()
                        .HasDatabaseName("IX_AIAssistantMaterialAssetJobs_Material_Asset");

                    b.ToTable("AIAssistantMaterialAssetJobs");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.AIAssistantSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AIAssistantMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("AssetHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("active");

                    b.HasKey("Id");

                    b.HasIndex("AIAssistantMaterialId")
                        .IsUnique();

                    b.ToTable("AIAssistantSessions");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiAvailable")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("notready");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContentHash"), "ascii");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Filetype")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("JobId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Src")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("URL")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.HasIndex("AiAvailable")
                        .HasDatabaseName("idx_ai_available");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ux_assets_content_hash");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.ChecklistEntry", b =>
                {
                    b.Property<int>("ChecklistEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChecklistEntryId"));

                    b.Property<int>("ChecklistMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("ChecklistEntryId");

                    b.HasIndex("ChecklistMaterialId")
                        .HasDatabaseName("idx_checklist_material");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.Group", b =>
                {
                    b.Property<string>("GroupName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenantName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("GroupName");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.GroupUser", b =>
                {
                    b.Property<string>("GroupName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("GroupName", "UserName");

                    b.HasIndex("GroupName")
                        .HasDatabaseName("idx_group");

                    b.HasIndex("UserName")
                        .HasDatabaseName("idx_user");

                    b.ToTable("GroupUsers");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.ImageAnnotation", b =>
                {
                    b.Property<int>("ImageAnnotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ImageAnnotationId"));

                    b.Property<string>("ClientId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("FontSize")
                        .HasColumnType("int");

                    b.Property<int>("ImageMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<double>("X")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Y")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValue(0.0);

                    b.HasKey("ImageAnnotationId");

                    b.HasIndex("ImageMaterialId")
                        .HasDatabaseName("idx_image_material");

                    b.ToTable("ImageAnnotations");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.InnovChatbotMaterialAssetJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("CollectionName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("InnovChatbotMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Pilot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pending");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("InnovChatbotMaterialId", "AssetId")
                        .IsUnique()
                        .HasDatabaseName("IX_InnovChatbotMaterialAssetJobs_Material_Asset");

                    b.ToTable("InnovChatbotMaterialAssetJobs");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.LearningPath", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("LearningPathName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.ToTable("LearningPaths");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.Material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("Created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("Unique_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("datetime");

                    b.HasKey("id");

                    b.HasIndex("Discriminator")
                        .HasDatabaseName("idx_discriminator");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_type");

                    b.HasIndex("Unique_id")
                        .HasDatabaseName("idx_unique_id");

                    b.ToTable("Materials");

                    b.HasDiscriminator().HasValue("Material");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.MaterialRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RelationshipType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("inherit_from_program")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("max_level_rank")
                        .HasColumnType("int");

                    b.Property<int?>("min_level_rank")
                        .HasColumnType("int");

                    b.Property<int?>("required_upto_level_rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("idx_id");

                    b.HasIndex("RelationshipType")
                        .HasDatabaseName("idx_relationship_type");

                    b.HasIndex("RelatedEntityId", "RelatedEntityType")
                        .HasDatabaseName("idx_related_entity");

                    b.ToTable("MaterialRelationships");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.ProgramLearningPath", b =>
                {
                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("int");

                    b.Property<int>("LearningPathId")
                        .HasColumnType("int");

                    b.Property<bool?>("inherit_from_program")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int?>("max_level_rank")
                        .HasColumnType("int");

                    b.Property<int?>("min_level_rank")
                        .HasColumnType("int");

                    b.Property<int?>("required_upto_level_rank")
                        .HasColumnType("int");

                    b.HasKey("TrainingProgramId", "LearningPathId");

                    b.HasIndex("LearningPathId")
                        .HasDatabaseName("idx_path");

                    b.HasIndex("TrainingProgramId")
                        .HasDatabaseName("idx_program");

                    b.ToTable("ProgramLearningPaths");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.ProgramMaterial", b =>
                {
                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<bool?>("inherit_from_program")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int?>("max_level_rank")
                        .HasColumnType("int");

                    b.Property<int?>("min_level_rank")
                        .HasColumnType("int");

                    b.Property<int?>("required_upto_level_rank")
                        .HasColumnType("int");

                    b.HasKey("TrainingProgramId", "MaterialId");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("idx_material");

                    b.HasIndex("TrainingProgramId")
                        .HasDatabaseName("idx_program");

                    b.ToTable("ProgramMaterials");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.QuestionnaireEntry", b =>
                {
                    b.Property<int>("QuestionnaireEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QuestionnaireEntryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("QuestionnaireMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("QuestionnaireEntryId");

                    b.HasIndex("QuestionnaireMaterialId")
                        .HasDatabaseName("idx_questionnaire_material");

                    b.ToTable("QuestionnaireEntries");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.QuizAnswer", b =>
                {
                    b.Property<int>("QuizAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QuizAnswerId"));

                    b.Property<bool>("CorrectAnswer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Extra")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("QuizAnswerId");

                    b.HasIndex("QuizQuestionId")
                        .HasDatabaseName("idx_quiz_question");

                    b.ToTable("QuizAnswers");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.QuizQuestion", b =>
                {
                    b.Property<int>("QuizQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QuizQuestionId"));

                    b.Property<bool>("AllowMultiple")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("HelpText")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("text");

                    b.Property<int>("QuizMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("ScaleConfig")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("QuizQuestionId");

                    b.HasIndex("QuizMaterialId")
                        .HasDatabaseName("idx_quiz_material");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.Share", b =>
                {
                    b.Property<string>("ShareId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FileId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ShareId");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.SubcomponentMaterialRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("RelatedMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("RelationshipType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SubcomponentId")
                        .HasColumnType("int");

                    b.Property<string>("SubcomponentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMaterialId")
                        .HasDatabaseName("idx_material");

                    b.HasIndex("SubcomponentId", "SubcomponentType")
                        .HasDatabaseName("idx_subcomponent");

                    b.HasIndex("SubcomponentId", "SubcomponentType", "RelatedMaterialId")
                        .IsUnique()
                        .HasDatabaseName("idx_unique_relationship");

                    b.ToTable("SubcomponentMaterialRelationships");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.TenantAdmin", b =>
                {
                    b.Property<string>("TenantName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("TenantName", "UserName");

                    b.HasIndex("TenantName")
                        .HasDatabaseName("idx_tenant");

                    b.HasIndex("UserName")
                        .HasDatabaseName("idx_user");

                    b.ToTable("TenantAdmins");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.TrainingProgram", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Created_at")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Objectives")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Requirements")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("max_level_rank")
                        .HasColumnType("int");

                    b.Property<int?>("min_level_rank")
                        .HasColumnType("int");

                    b.Property<int?>("required_upto_level_rank")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("admin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.UserMaterialData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int?>("LearningPathId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LearningPathId")
                        .HasDatabaseName("idx_learning_path_id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("idx_material_id");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("idx_program_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_id");

                    b.HasIndex("UserId", "MaterialId", "ProgramId")
                        .IsUnique()
                        .HasDatabaseName("idx_user_material_program");

                    b.ToTable("UserMaterialData");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.UserMaterialScore", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("LearningPathId")
                        .HasColumnType("int");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("UserId", "MaterialId", "ProgramId");

                    b.HasIndex("LearningPathId")
                        .HasDatabaseName("idx_learning_path_id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("idx_material_id");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("idx_program_id");

                    b.ToTable("UserMaterialScores");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.VideoTimestamp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("type");

                    b.Property<int>("VideoMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("endTime")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("startTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.HasIndex("VideoMaterialId")
                        .HasDatabaseName("idx_video_material");

                    b.ToTable("Timestamps");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.WorkflowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("WorkflowMaterialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowMaterialId")
                        .HasDatabaseName("idx_workflow_material");

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.XR50Tenant", b =>
                {
                    b.Property<string>("TenantName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenantDirectory")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TenantGroup")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenantSchema")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("TenantName");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.AIAssistantMaterial", b =>
                {
                    b.HasBaseType("XR50TrainingAssetRepo.Models.Material");

                    b.Property<string>("AIAssistantAssetIds")
                        .HasColumnType("text")
                        .HasColumnName("AIAssistantAssetIds");

                    b.Property<string>("AIAssistantStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("notready")
                        .HasColumnName("AIAssistantStatus");

                    b.Property<string>("CollectionName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ServiceJobId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ServiceJobId");

                    b.HasDiscriminator().HasValue("AIAssistantMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.ChatbotMaterial", b =>
                {
                    b.HasBaseType("XR50TrainingAssetRepo.Models.Material");

                    b.Property<string>("ChatbotConfig")
                        .HasColumnType("text")
                        .HasColumnName("ChatbotConfig");

                    b.Property<string>("ChatbotModel")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ChatbotModel");

                    b.Property<string>("ChatbotPrompt")
                        .HasColumnType("text")
                        .HasColumnName("ChatbotPrompt");

                    b.HasDiscriminator().HasValue("ChatbotMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.ChecklistMaterial", b =>
                {
                    b.HasBaseType("XR50TrainingAssetRepo.Models.Material");

                    b.HasDiscriminator().HasValue("ChecklistMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.DefaultMaterial", b =>
                {
                    b.HasBaseType("XR50TrainingAssetRepo.Models.Material");

                    b.Property<int?>("AssetId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AssetId");

                    b.HasDiscriminator().HasValue("DefaultMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.ImageMaterial", b =>
                {
                    b.HasBaseType("XR50TrainingAssetRepo.Models.Material");

                    b.Property<int?>("AssetId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AssetId");

                    b.Property<string>("ImageFormat")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ImageFormat");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("int")
                        .HasColumnName("ImageHeight");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ImagePath");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("int")
                        .HasColumnName("ImageWidth");

                    b.HasIndex("ImagePath")
                        .HasDatabaseName("idx_image_path");

                    b.HasDiscriminator().HasValue("ImageMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.InnovChatbotMaterial", b =>
                {
                    b.HasBaseType("XR50TrainingAssetRepo.Models.Material");

                    b.Property<string>("ExpertiseLevel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("InnovExpertiseLevel");

                    b.Property<string>("InnovAssetIds")
                        .HasColumnType("text")
                        .HasColumnName("InnovAssetIds");

                    b.Property<string>("InnovStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("notready")
                        .HasColumnName("InnovStatus");

                    b.Property<string>("Pilot")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("InnovPilot");

                    b.HasDiscriminator().HasValue("InnovChatbotMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.MQTT_TemplateMaterial", b =>
                {
                    b.HasBaseType("XR50TrainingAssetRepo.Models.Material");

                    b.Property<string>("message_text")
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<string>("message_type")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("message_type");

                    b.HasDiscriminator().HasValue("MQTT_TemplateMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.PDFMaterial", b =>
                {
                    b.HasBaseType("XR50TrainingAssetRepo.Models.Material");

                    b.Property<int?>("AssetId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AssetId");

                    b.Property<long?>("PdfFileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("PdfFileSize");

                    b.Property<int?>("PdfPageCount")
                        .HasColumnType("int")
                        .HasColumnName("PdfPageCount");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("PdfPath");

                    b.HasIndex("PdfPath")
                        .HasDatabaseName("idx_pdf_path");

                    b.HasDiscriminator().HasValue("PDFMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.QuestionnaireMaterial", b =>
                {
                    b.HasBaseType("XR50TrainingAssetRepo.Models.Material");

                    b.Property<decimal?>("PassingScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PassingScore");

                    b.Property<string>("QuestionnaireConfig")
                        .HasColumnType("text")
                        .HasColumnName("QuestionnaireConfig");

                    b.Property<string>("QuestionnaireType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("QuestionnaireType");

                    b.HasDiscriminator().HasValue("QuestionnaireMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.QuizMaterial", b =>
                {
                    b.HasBaseType("XR50TrainingAssetRepo.Models.Material");

                    b.Property<bool>("EvaluationMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int?>("MinScore")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("QuizMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.UnityMaterial", b =>
                {
                    b.HasBaseType("XR50TrainingAssetRepo.Models.Material");

                    b.Property<int?>("AssetId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AssetId");

                    b.Property<string>("UnityBuildTarget")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UnityBuildTarget");

                    b.Property<string>("UnityJson")
                        .HasColumnType("text");

                    b.Property<string>("UnitySceneName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UnitySceneName");

                    b.Property<string>("UnityVersion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UnityVersion");

                    b.HasDiscriminator().HasValue("UnityMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.VideoMaterial", b =>
                {
                    b.HasBaseType("XR50TrainingAssetRepo.Models.Material");

                    b.Property<string>("Annotations")
                        .HasColumnType("json")
                        .HasColumnName("Annotations");

                    b.Property<int?>("AssetId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AssetId");

                    b.Property<int?>("VideoDuration")
                        .HasColumnType("int")
                        .HasColumnName("VideoDuration");

                    b.Property<string>("VideoPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("VideoPath");

                    b.Property<string>("VideoResolution")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("VideoResolution");

                    b.Property<string>("startTime")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("startTime");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("idx_asset_id");

                    b.HasIndex("VideoPath")
                        .HasDatabaseName("idx_video_path");

                    b.HasDiscriminator().HasValue("VideoMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.WorkflowMaterial", b =>
                {
                    b.HasBaseType("XR50TrainingAssetRepo.Models.Material");

                    b.HasDiscriminator().HasValue("WorkflowMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.AIAssistantMaterialAssetJob", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.AIAssistantMaterial", "AIAssistantMaterial")
                        .WithMany()
                        .HasForeignKey("AIAssistantMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIAssistantMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.AIAssistantSession", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.AIAssistantMaterial", "AIAssistantMaterial")
                        .WithOne("CurrentSession")
                        .HasForeignKey("XR50TrainingAssetRepo.Models.AIAssistantSession", "AIAssistantMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIAssistantMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.ChecklistEntry", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.ChecklistMaterial", null)
                        .WithMany("Entries")
                        .HasForeignKey("ChecklistMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.GroupUser", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.Group", "Group")
                        .WithMany("GroupUsers")
                        .HasForeignKey("GroupName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XR50TrainingAssetRepo.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.ImageAnnotation", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.ImageMaterial", null)
                        .WithMany("ImageAnnotations")
                        .HasForeignKey("ImageMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.InnovChatbotMaterialAssetJob", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.InnovChatbotMaterial", "InnovChatbotMaterial")
                        .WithMany()
                        .HasForeignKey("InnovChatbotMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InnovChatbotMaterialAssetJobs_Materials");

                    b.Navigation("InnovChatbotMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.MaterialRelationship", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.Material", "Material")
                        .WithMany("MaterialRelationships")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.ProgramLearningPath", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.LearningPath", "LearningPath")
                        .WithMany("ProgramLearningPaths")
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XR50TrainingAssetRepo.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("LearningPaths")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningPath");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.ProgramMaterial", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.Material", "Material")
                        .WithMany("ProgramMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XR50TrainingAssetRepo.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("Materials")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.QuestionnaireEntry", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.QuestionnaireMaterial", null)
                        .WithMany("QuestionnaireEntries")
                        .HasForeignKey("QuestionnaireMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.QuizAnswer", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.QuizQuestion", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.QuizQuestion", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.QuizMaterial", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuizMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.SubcomponentMaterialRelationship", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.Material", "RelatedMaterial")
                        .WithMany()
                        .HasForeignKey("RelatedMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subcomponent_material");

                    b.Navigation("RelatedMaterial");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.TenantAdmin", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.XR50Tenant", "Tenant")
                        .WithMany("TenantAdmins")
                        .HasForeignKey("TenantName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("XR50TrainingAssetRepo.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.UserMaterialData", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.LearningPath", "LearningPath")
                        .WithMany()
                        .HasForeignKey("LearningPathId");

                    b.HasOne("XR50TrainingAssetRepo.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XR50TrainingAssetRepo.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningPath");

                    b.Navigation("Material");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.UserMaterialScore", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.LearningPath", "LearningPath")
                        .WithMany()
                        .HasForeignKey("LearningPathId");

                    b.HasOne("XR50TrainingAssetRepo.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XR50TrainingAssetRepo.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningPath");

                    b.Navigation("Material");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.VideoTimestamp", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.VideoMaterial", null)
                        .WithMany("Timestamps")
                        .HasForeignKey("VideoMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.WorkflowStep", b =>
                {
                    b.HasOne("XR50TrainingAssetRepo.Models.WorkflowMaterial", null)
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("WorkflowMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.Group", b =>
                {
                    b.Navigation("GroupUsers");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.LearningPath", b =>
                {
                    b.Navigation("ProgramLearningPaths");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.Material", b =>
                {
                    b.Navigation("MaterialRelationships");

                    b.Navigation("ProgramMaterials");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.QuizQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.TrainingProgram", b =>
                {
                    b.Navigation("LearningPaths");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.XR50Tenant", b =>
                {
                    b.Navigation("TenantAdmins");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.AIAssistantMaterial", b =>
                {
                    b.Navigation("CurrentSession");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.ChecklistMaterial", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.ImageMaterial", b =>
                {
                    b.Navigation("ImageAnnotations");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.QuestionnaireMaterial", b =>
                {
                    b.Navigation("QuestionnaireEntries");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.QuizMaterial", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.VideoMaterial", b =>
                {
                    b.Navigation("Timestamps");
                });

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.WorkflowMaterial", b =>
                {
                    b.Navigation("WorkflowSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
