// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XR50TrainingAssetRepo.Data;

#nullable disable

namespace XR50TrainingAssetRepo.Migrations.Registry
{
    [DbContext(typeof(XR50RegistryContext))]
    [Migration("20260820141430_RegistryBaseline")]
    partial class RegistryBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("XR50TrainingAssetRepo.Models.XR50TenantRegistryEntry", b =>
                {
                    b.Property<string>("TenantName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DefaultAICollection")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("HubTenantId")
                        .HasColumnType("char(36)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("HubTenantId"), "utf8mb4");

                    b.Property<string>("InnovChatbotApiToken")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("InnovChatbotBaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("InnovChatbotDefaultPilot")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("OwnerName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("S3BucketArn")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("S3BucketName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("S3BucketRegion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StorageEndpoint")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("OwnCloud");

                    b.Property<string>("TenantDirectory")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TenantGroup")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TenantName");

                    b.HasIndex("HubTenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_registry_hub_tenant");

                    b.ToTable("XR50TenantRegistry", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
